version: '3.8'

services:
  histudent-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://johndoe:randompassword@histudent-db:5432/mydb?schema=histudent
      - NEXT_PUBLIC_SOCKET_URL=https://histudent.eduarchive.duckdns.org
    labels:
      - traefik.enable=true
      - traefik.http.routers.histudent.rule=Host(`histudent.eduarchive.duckdns.org`)
    depends_on:
      histudent-db:
        condition: service_healthy
    restart: unless-stopped

  histudent-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U johndoe -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
